eureka:
  client:
    service-url:
      defaultZone: http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
#    register-with-eureka: false
  server:
    # 关闭自我保护
    enable-self-preservation: false
spring:
  application:
    name: eureka
server:
  port: 8761